site_name: Mirai Python Loader
site_description: 说明文档
site_author: Nana
repo_url: https://github.com/example/repository/
theme:
  name: 'material'
  language: 'zh'
  features:
    - header.autohide
  palette:
    - scheme: default
      primary: cyan
      accent: cyan
      toggle:
        icon: material/toggle-switch-off-outline
        name: 切换夜间模式
    - scheme: slate
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: 切换日间模式


plugins:
  - search:
      lang: ['en','jp']
  - mkdocstrings
nav:
  - 主页: index.md
  - 使用MPL:
      - 环境安装: user/environment.md
      - 启动MPL: user/use.md
      - 安装插件: user/plugin.md
  - 插件开发:
      - 准备: developer/preface.md
      - 基本开发: developer/base.md
      - 创建插件任务: developer/task.md
      - 异常捕获: developer/exception.md
      - 日志对象: developer/logger.md
      - 配置: developer/config.md
      - 连接数据库: developer/db.md
      - 文件IO: developer/file.md
      - 权限管理: developer/permission.md
      - 开发包模块详情:
          - __init__: developer/moudle/__init__.md
          - plugin: developer/moudle/plugin.md
          - mirai: developer/moudle/mirai.md
          - msg: developer/moudle/msg.md
          - config: developer/moudle/config.md
